### ISSUE TITLE
Getting error message on Dashboard

### ISSUE THREAD

**Issue by chap00us** [notoriousbdg/vrops-dashboard-reclaimable_resources_details#1]
Error Message:

No such metric reclaimable\|orphaned_disk\|cost

Just upgraded today to vROPs 8.1 and followed the instructions listed for the dashboard. Get the message when selecting any object.

**Comment by notoriousbdg** [comment]
Which step is giving you that error?

**Comment by chap00us** [comment]
Thanks for responding. The error pops up when I use the imported dashboard. The Potential Savings widget does not load. It seems like maybe some of the Super Metrics may not have loaded? Unfortunately I am not as familiar with this product as others so I might just be missing something simple.

Eric Chapin

**Comment by notoriousbdg** [comment]
Can you check the super metrics to ensure that "Potential Savings from Orphaned Disks" is enabled for Custom Datacenter, Cluster Compute Resource, vSphere World, and Datacenter objects?

**Comment by chap00us** [comment]
Looks like it is all set correctly.

Eric Chapin

**Comment by notoriousbdg** [comment]
I had another person that ran into this issue.  Please go to the Reclaim page, click on the gear icon, and enable Orphaned Disks.  Once you do that, let it sit overnight then attempt to view the dashboard again.

**Comment by cleif** [comment]
Hi @notoriousbdg - Is that orphaned disks option only available in 8.1?  We are still on 8.0.1, and I do not see the gear option on the "reclaim" page to enable Orphaned disks.
